const CATALOG_DEFS = {
  ai_recommended_movies: { name:"🤖 AI Recommended Movies", type:"movie", handler:"gemini_ai_recommended" },
  ai_recommended_series: { name:"🤖 AI Recommended Series", type:"series", handler:"gemini_ai_recommended" },
  trending_movies:    { name:"Trending",        type:"movie",  handler:"tmdb_trending" },
  trending_series:    { name:"Trending",        type:"series", handler:"tmdb_trending" },
  popular_movies:     { name:"Popular",         type:"movie",  handler:"tmdb_source", source:"popular" },
  popular_series:     { name:"Popular",         type:"series", handler:"tmdb_source", source:"popular" },
  top_movies:         { name:"Top Rated",       type:"movie",  handler:"tmdb_source", source:"top_rated" },
  top_series:         { name:"Top Rated",       type:"series", handler:"tmdb_source", source:"top_rated" },
  now_movies:         { name:"Now Playing",            type:"movie",  handler:"tmdb_source", source:"now_playing" },
  airing_series:      { name:"Airing Today",           type:"series", handler:"tmdb_source", source:"airing_today" },
  ontheair_series:    { name:"On The Air",             type:"series", handler:"tmdb_source", source:"on_the_air" },
  anime_movies:       { name:"Anime",           type:"movie",  handler:"tmdb_anime" },
  anime_series:       { name:"Anime",           type:"series", handler:"tmdb_anime" },
  bollywood_movies:   { name:"Bollywood",       type:"movie",  handler:"tmdb_bollywood" },
  bollywood_series:   { name:"Bollywood",       type:"series", handler:"tmdb_bollywood" },
  paramount_movies:   { name:"Paramount",       type:"movie",  handler:"tmdb_paramount" },
  paramount_series:   { name:"Paramount",       type:"series", handler:"tmdb_paramount" },
  netflix_movies:     { name:"Netflix",         type:"movie",  handler:"tmdb_provider", provider: 8 },
  netflix_series:     { name:"Netflix",         type:"series", handler:"tmdb_provider", provider: 8 },
  amazon_movies:      { name:"Amazon",          type:"movie",  handler:"tmdb_provider", provider: 9 },
  amazon_series:      { name:"Amazon",          type:"series", handler:"tmdb_provider", provider: 9 },
  disney_movies:      { name:"Disney+",         type:"movie",  handler:"tmdb_provider", provider: 337 },
  disney_series:      { name:"Disney+",         type:"series", handler:"tmdb_provider", provider: 337 },
  hbo_movies:         { name:"HBO",             type:"movie",  handler:"tmdb_provider", provider: 1899 },
  hbo_series:         { name:"HBO",             type:"series", handler:"tmdb_provider", provider: 1899 },
  apple_movies:       { name:"Apple TV+",       type:"movie",  handler:"tmdb_provider", provider: 350 },
  apple_series:       { name:"Apple TV+",       type:"series", handler:"tmdb_provider", provider: 350 },
  peacock_movies:     { name:"Peacock",         type:"movie",  handler:"tmdb_provider", provider: 386 },
  peacock_series:     { name:"Peacock",         type:"series", handler:"tmdb_provider", provider: 386 },
  mgm_movies:         { name:"MGM+",            type:"movie",  handler:"tmdb_provider", provider: 268 },
  acorn_movies:       { name:"Acorn",           type:"movie",  handler:"tmdb_provider", provider: 87 },
  acorn_series:       { name:"Acorn",           type:"series", handler:"tmdb_provider", provider: 87 },
  shudder_movies:     { name:"Shudder",         type:"movie",  handler:"tmdb_provider", provider: 99 },
  shudder_series:     { name:"Shudder",         type:"series", handler:"tmdb_provider", provider: 99 },
  britbox_movies:     { name:"BritBox",         type:"movie",  handler:"tmdb_provider", provider: 151 },
  britbox_series:     { name:"BritBox",         type:"series", handler:"tmdb_provider", provider: 151 },
  itvx_movies:        { name:"ITVX",            type:"movie",  handler:"tmdb_provider", provider: 584 },
  itvx_series:        { name:"ITVX",            type:"series", handler:"tmdb_provider", provider: 584 },
  channel4_movies:    { name:"Channel 4",       type:"movie",  handler:"tmdb_provider", provider: 583 },
  channel4_series:    { name:"Channel 4",       type:"series", handler:"tmdb_provider", provider: 583 },
  crunchyroll_movies: { name:"Crunchyroll",     type:"movie",  handler:"tmdb_provider", provider: 283 },
  crunchyroll_series: { name:"Crunchyroll",     type:"series", handler:"tmdb_provider", provider: 283 },
  hidive_movies:      { name:"Hidive",          type:"movie",  handler:"tmdb_provider", provider: 430 },
  hidive_series:      { name:"Hidive",          type:"series", handler:"tmdb_provider", provider: 430 },
  hulu_movies:        { name:"Hulu",            type:"movie",  handler:"tmdb_provider", provider: 15 },
  hulu_series:        { name:"Hulu",            type:"series", handler:"tmdb_provider", provider: 15 },
  discovery_movies:   { name:"Discovery+",      type:"movie",  handler:"tmdb_provider", provider: 520 },
  discovery_series:   { name:"Discovery+",      type:"series", handler:"tmdb_provider", provider: 520 },
  natgeo_movies:      { name:"National Geographic", type:"movie",  handler:"tmdb_provider", provider: 1964 },
  natgeo_series:      { name:"National Geographic", type:"series", handler:"tmdb_provider", provider: 1964 },
  ae_series:          { name:"A&E",             type:"series", handler:"tmdb_provider", provider: 156 },
  animalplanet_series:{ name:"Animal Planet",   type:"series", handler:"tmdb_provider", provider: 399 },
  action_movies:      { name:"Action",          type:"movie",  handler:"tmdb_genre", genre: 28 },
  action_series:      { name:"Action",          type:"series", handler:"tmdb_genre", genre: 28 },
  comedy_movies:      { name:"Comedy",          type:"movie",  handler:"tmdb_genre", genre: 35 },
  comedy_series:      { name:"Comedy",          type:"series", handler:"tmdb_genre", genre: 35 },
  horror_movies:      { name:"Horror",          type:"movie",  handler:"tmdb_genre", genre: 27 },
  horror_series:      { name:"Horror",          type:"series", handler:"tmdb_genre", genre: 27 },
  scifi_movies:       { name:"Sci-Fi",          type:"movie",  handler:"tmdb_genre", genre: 878 },
  scifi_series:       { name:"Sci-Fi",          type:"series", handler:"tmdb_genre", genre: 878 },
  documentary_movies: { name:"Documentary",     type:"movie",  handler:"tmdb_genre", genre: 99 },
  documentary_series: { name:"Documentary",     type:"series", handler:"tmdb_genre", genre: 99 },
  romance_movies:     { name:"Romance",         type:"movie",  handler:"tmdb_genre", genre: 10749 },
  romance_series:     { name:"Romance",         type:"series", handler:"tmdb_genre", genre: 10749 },
  thriller_movies:    { name:"Thriller",        type:"movie",  handler:"tmdb_genre", genre: 53 },
  thriller_series:    { name:"Thriller",        type:"series", handler:"tmdb_genre", genre: 53 },
  crime_movies:       { name:"Crime",           type:"movie",  handler:"tmdb_genre", genre: 80 },
  crime_series:       { name:"Crime",           type:"series", handler:"tmdb_genre", genre: 80 },
  animation_movies:   { name:"Animated",        type:"movie",  handler:"tmdb_genre", genre: 16 },
  animation_series:   { name:"Animated",        type:"series", handler:"tmdb_genre", genre: 16 },
  family_movies:      { name:"Family",          type:"movie",  handler:"tmdb_genre", genre: 10751 },
  family_series:      { name:"Family",          type:"series", handler:"tmdb_genre", genre: 10751 },
  fantasy_movies:     { name:"Fantasy",         type:"movie",  handler:"tmdb_genre", genre: 14 },
  fantasy_series:     { name:"Fantasy",         type:"series", handler:"tmdb_genre", genre: 14 },
  mystery_movies:     { name:"Mystery",         type:"movie",  handler:"tmdb_genre", genre: 9648 },
  mystery_series:     { name:"Mystery",         type:"series", handler:"tmdb_genre", genre: 9648 },
  drama_movies:       { name:"Drama",           type:"movie",  handler:"tmdb_genre", genre: 18 },
  drama_series:       { name:"Drama",           type:"series", handler:"tmdb_genre", genre: 18 },
  theme_superhero:    { name:"Superhero",              type:"movie",  handler:"tmdb_keyword", keyword: 9715,  lang:"en" },
  theme_heist:        { name:"Heist",                  type:"movie",  handler:"tmdb_keyword", keyword: 10051, lang:"en" },
  theme_serialkiller: { name:"Serial Killer",          type:"movie",  handler:"tmdb_keyword", keyword: 10714, lang:"en" },
  theme_timeloop:     { name:"Time Loop",              type:"movie",  handler:"tmdb_keyword", keyword: 10854, lang:"en" },
  theme_mafia:      { name:"Mafia",      type:"movie", handler:"tmdb_keyword", keyword:10391, lang:"en" },
  theme_gangster:   { name:"Gangster",   type:"movie", handler:"tmdb_keyword", keyword:3149,  lang:"en" },
  theme_detective:  { name:"Detective",  type:"movie", handler:"tmdb_keyword", keyword:703,   lang:"en" },
  theme_police:     { name:"Police",     type:"movie", handler:"tmdb_keyword", keyword:6149,  lang:"en" },
  theme_prison:     { name:"Prison",     type:"movie", handler:"tmdb_keyword", keyword:378,   lang:"en" },
  theme_murder:     { name:"Murder Mystery", type:"movie", handler:"tmdb_keyword", keyword:9826, lang:"en" },
  theme_zombie:       { name:"Zombie",                 type:"movie",  handler:"tmdb_keyword", keyword: 12377, lang:"en" },
  theme_slasher:            { name:"Slasher",               type:"movie",  handler:"tmdb_keyword", keyword: 12339,  lang:"en" },
  theme_paranormal:         { name:"Paranormal",            type:"movie",  handler:"tmdb_keyword", keyword: 9853,   lang:"en" },
  theme_possession:         { name:"Possession",            type:"movie",  handler:"tmdb_keyword", keyword: 9712,   lang:"en" },
  theme_foundfootage:       { name:"Found Footage",         type:"movie",  handler:"tmdb_keyword", keyword: 163053, lang:"en" },
  theme_homeinvasion:       { name:"Home Invasion",         type:"movie",  handler:"tmdb_keyword", keyword: 14903,  lang:"en" },
  theme_creaturefeature:    { name:"Creature Feature",      type:"movie",  handler:"tmdb_keyword", keyword: 158126, lang:"en" },
  theme_psychological:      { name:"Psychological Horror",  type:"movie",  handler:"tmdb_keyword", keyword: 295907, lang:"en" },
  theme_horrorcomedy:       { name:"Horror Comedy",         type:"movie",  handler:"tmdb_keyword", keyword: 373400, lang:"en" },
  theme_folkhorror:         { name:"Folk Horror",           type:"movie",  handler:"tmdb_keyword", keyword: 209568, lang:"en" },
  theme_gothichorror:       { name:"Gothic Horror",         type:"movie",  handler:"tmdb_keyword", keyword: 15032,  lang:"en" },
  theme_bodyhorror:         { name:"Body Horror",           type:"movie",  handler:"tmdb_keyword", keyword: 283085, lang:"en" },
  theme_cosmichorror:       { name:"Cosmic Horror",         type:"movie",  handler:"tmdb_keyword", keyword: 215959, lang:"en" },
  theme_lovecraftian:       { name:"Lovecraftian Horror",   type:"movie",  handler:"tmdb_keyword", keyword: 287274, lang:"en" },
  theme_animalattack:       { name:"Animal Attack",         type:"movie",  handler:"tmdb_keyword", keyword: 5160,   lang:"en" },
  theme_werewolf:           { name:"Werewolf",              type:"movie",  handler:"tmdb_keyword", keyword: 12564,  lang:"en" },
  theme_vampire:            { name:"Vampire",               type:"movie",  handler:"tmdb_keyword", keyword: 3133,   lang:"en" },
  studio_marvel:      { name:"Marvel",                 type:"movie",  handler:"tmdb_company", company: 420 },
  studio_dc:          { name:"DC Films",               type:"movie",  handler:"tmdb_company", company: "429|128064|9993", excludeAnimation: true },
  studio_a24:         { name:"A24",                    type:"movie",  handler:"tmdb_company", company: 41077 },
  studio_blumhouse:   { name:"Blumhouse",              type:"movie",  handler:"tmdb_company", company: 3172 },
  studio_ghibli:      { name:"Studio Ghibli",          type:"movie",  handler:"tmdb_company", company: 10342 },
  studio_wb:          { name:"Warner Bros",              type:"movie",  handler:"tmdb_company", company: "174" },
  studio_universal:   { name:"Universal Pictures",        type:"movie",  handler:"tmdb_company", company: "33" },
  studio_sony:        { name:"Sony Pictures",             type:"movie",  handler:"tmdb_company", company: "34|5" },
  studio_paramount:   { name:"Paramount Pictures",        type:"movie",  handler:"tmdb_company", company: "4" },
  studio_20thcentury: { name:"20th Century",              type:"movie",  handler:"tmdb_company", company: "25" },
  studio_lionsgate:   { name:"Lionsgate",                 type:"movie",  handler:"tmdb_company", company: "1632" },
  studio_newline:     { name:"New Line Cinema",           type:"movie",  handler:"tmdb_company", company: "12" },
  studio_canalplus:   { name:"Canal+",                    type:"movie",  handler:"tmdb_company", company: "104" },
  network_abc:        { name:"ABC",                       type:"series", handler:"tmdb_network", networkId: 2 },
  network_cbs:        { name:"CBS",                       type:"series", handler:"tmdb_network", networkId: 16 },
  network_fox:        { name:"FOX",                       type:"series", handler:"tmdb_network", networkId: 19 },
  network_nbc:        { name:"NBC",                       type:"series", handler:"tmdb_network", networkId: 6 },
  starz_series:       { name:"Starz",                     type:"series", handler:"tmdb_network", networkId: 318 },
  network_nickelodeon:{ name:"Nickelodeon",              type:"series", handler:"tmdb_network", networkId: 13 },
  network_nickjr:     { name:"Nick Jr",                  type:"series", handler:"tmdb_network", networkId: 35 },
  startrek_coll:      { name:"Star Trek",                 type:"movie",  handler:"tmdb_multi_collection", collectionIds: [151, 115570, 115575] },
  director_nolan:     { name:"Christopher Nolan",      type:"movie",  handler:"tmdb_director", personId: 525 },
  director_scorsese:  { name:"Martin Scorsese",         type:"movie",  handler:"tmdb_director", personId: 1032 },
  director_spielberg: { name:"Steven Spielberg",        type:"movie",  handler:"tmdb_director", personId: 488 },
  director_villeneuve:{ name:"Denis Villeneuve",        type:"movie",  handler:"tmdb_director", personId: 137427 },
  director_fincher:   { name:"David Fincher",           type:"movie",  handler:"tmdb_director", personId: 7467 },
  director_kubrick:   { name:"Stanley Kubrick",         type:"movie",  handler:"tmdb_director", personId: 240 },
  director_hitchcock: { name:"Alfred Hitchcock",        type:"movie",  handler:"tmdb_director", personId: 2636 },
  director_anderson:  { name:"Wes Anderson",            type:"movie",  handler:"tmdb_director", personId: 5655 },
  director_burton:    { name:"Tim Burton",              type:"movie",  handler:"tmdb_director", personId: 510 },
  director_tarantino: { name:"Quentin Tarantino",       type:"movie",  handler:"tmdb_director", personId: 138 },
  director_hughes:    { name:"John Hughes",              type:"movie",  handler:"tmdb_director", personId: 11505 },
  actor_sandler:         { name:"Adam Sandler",               type:"movie",  handler:"tmdb_actor", personId: 19292 },
  actor_jolie:         { name:"Angelina Jolie",               type:"movie",  handler:"tmdb_actor", personId: 11701 },
  actor_pitt:         { name:"Brad Pitt",               type:"movie",  handler:"tmdb_actor", personId: 287 },
  actor_bale:         { name:"Christian Bale",               type:"movie",  handler:"tmdb_actor", personId: 3894 },
  actor_eastwood:         { name:"Clint Eastwood",               type:"movie",  handler:"tmdb_actor", personId: 190 },
  actor_denzel:         { name:"Denzel Washington",               type:"movie",  handler:"tmdb_actor", personId: 5292 },
  actor_carrey:         { name:"Jim Carrey",               type:"movie",  handler:"tmdb_actor", personId: 206 },
  actor_depp:         { name:"Johnny Depp",               type:"movie",  handler:"tmdb_actor", personId: 85 },
  actor_dicaprio:         { name:"Leonardo DiCaprio",               type:"movie",  handler:"tmdb_actor", personId: 6193 },
  actor_robbie:         { name:"Margot Robbie",               type:"movie",  handler:"tmdb_actor", personId: 234352 },
  actor_damon:         { name:"Matt Damon",               type:"movie",  handler:"tmdb_actor", personId: 1892 },
  actor_freeman:         { name:"Morgan Freeman",               type:"movie",  handler:"tmdb_actor", personId: 192 },
  actor_deniro:         { name:"Robert De Niro",               type:"movie",  handler:"tmdb_actor", personId: 380 },
  actor_rdj:         { name:"Robert Downey Jr",               type:"movie",  handler:"tmdb_actor", personId: 3223 },
  actor_gosling:         { name:"Ryan Gosling",               type:"movie",  handler:"tmdb_actor", personId: 30614 },
  actor_reynolds:         { name:"Ryan Reynolds",               type:"movie",  handler:"tmdb_actor", personId: 10859 },
  actor_rogen:         { name:"Seth Rogen",               type:"movie",  handler:"tmdb_actor", personId: 19274 },
  actor_cruise:         { name:"Tom Cruise",               type:"movie",  handler:"tmdb_actor", personId: 500 },
  actor_hanks:         { name:"Tom Hanks",               type:"movie",  handler:"tmdb_actor", personId: 31 },
  actor_ferrell:         { name:"Will Ferrell",               type:"movie",  handler:"tmdb_actor", personId: 23659 },
  actor_smith:         { name:"Will Smith",               type:"movie",  handler:"tmdb_actor", personId: 2888 },
  hp_collection:      { name:"Harry Potter",          type:"movie",  handler:"tmdb_collection", collectionId: 1241 },
  lotr_collection:    { name:"Lord of the Rings",       type:"movie",  handler:"tmdb_collection", collectionId: 119 },
  starwars_collection:{ name:"Star Wars",               type:"movie",  handler:"tmdb_collection", collectionId: 10 },
  bond_collection:    { name:"James Bond",              type:"movie",  handler:"tmdb_collection", collectionId: 645 },
  fastfurious_coll:   { name:"Fast & Furious",         type:"movie",  handler:"tmdb_collection", collectionId: 9485 },
  johnwick_coll:      { name:"John Wick",               type:"movie",  handler:"tmdb_collection", collectionId: 404609 },
  mi_collection:      { name:"Mission Impossible",      type:"movie",  handler:"tmdb_collection", collectionId: 87359 },
  indiana_collection: { name:"Indiana Jones",           type:"movie",  handler:"tmdb_collection", collectionId: 84 },
  jurassic_coll:      { name:"Jurassic Park",           type:"movie",  handler:"tmdb_collection", collectionId: 328 },
  hobbit_collection:  { name:"The Hobbit",              type:"movie",  handler:"tmdb_collection", collectionId: 121938 },
  avengers_coll:      { name:"The Avengers",            type:"movie",  handler:"tmdb_collection", collectionId: 86311 },
  xmen_collection:    { name:"X-Men",                   type:"movie",  handler:"tmdb_collection", collectionId: 748 },
  hungergames_coll:   { name:"Hunger Games",            type:"movie",  handler:"tmdb_collection", collectionId: 131635 },
  pirates_collection: { name:"Pirates of Caribbean",   type:"movie",  handler:"tmdb_collection", collectionId: 295 },
  shrek_collection:   { name:"Shrek",                  type:"movie",  handler:"tmdb_collection", collectionId: 2150 },
  iceage_collection:  { name:"Ice Age",                type:"movie",  handler:"tmdb_collection", collectionId: 8354 },
  httyd_collection:   { name:"How To Train Your Dragon",type:"movie",  handler:"tmdb_collection", collectionId: 89137 },
  madmax_collection:  { name:"Mad Max",                type:"movie",  handler:"tmdb_collection", collectionId: 8945 },
  bourne_collection:  { name:"The Bourne",             type:"movie",  handler:"tmdb_collection", collectionId: 31562 },
  oceans_collection:  { name:"Ocean's",              type:"movie",  handler:"tmdb_collection", collectionId: 304 },
  transformers_coll:  { name:"Transformers",           type:"movie",  handler:"tmdb_collection", collectionId: 8650 },
  captainamerica_coll:{ name:"Captain America",        type:"movie",  handler:"tmdb_collection", collectionId: 131295 },
  ironman_collection: { name:"Iron Man",               type:"movie",  handler:"tmdb_collection", collectionId: 131292 },
  gotg_collection:    { name:"Guardians of the Galaxy",type:"movie",  handler:"tmdb_collection", collectionId: 284433 },
  doctorstrange_coll: { name:"Doctor Strange",         type:"movie",  handler:"tmdb_collection", collectionId: 618529 },
  blackpanther_coll:  { name:"Black Panther",          type:"movie",  handler:"tmdb_collection", collectionId: 529892 },
  antman_collection:  { name:"Ant-Man",                type:"movie",  handler:"tmdb_collection", collectionId: 422834 },
  wonderwoman_coll:   { name:"Wonder Woman",           type:"movie",  handler:"tmdb_collection", collectionId: 468552 },
  aquaman_collection: { name:"Aquaman",                type:"movie",  handler:"tmdb_collection", collectionId: 573693 },
  planetapes_coll:    { name:"Planet of the Apes",     type:"movie",  handler:"tmdb_collection", collectionId: 1709 },
  kingsman_coll:      { name:"Kingsman",               type:"movie",  handler:"tmdb_collection", collectionId: 391860 },
  taken_collection:   { name:"Taken",                 type:"movie",  handler:"tmdb_collection", collectionId: 135483 },
  alien_collection:   { name:"Alien",                 type:"movie",  handler:"tmdb_collection", collectionId: 8091 },
  terminator_coll:    { name:"Terminator",            type:"movie",  handler:"tmdb_collection", collectionId: 528 },
  predator_coll:      { name:"Predator",              type:"movie",  handler:"tmdb_collection", collectionId: 399 },
  thor_collection:    { name:"Thor",                  type:"movie",  handler:"tmdb_collection", collectionId: 131296 },
  halloween_coll:     { name:"Halloween",             type:"movie",  handler:"tmdb_collection", collectionId: 91361 },
  nightmare_coll:     { name:"Nightmare on Elm Street",type:"movie", handler:"tmdb_collection", collectionId: 8581 },
  saw_collection:     { name:"Saw",                   type:"movie",  handler:"tmdb_collection", collectionId: 656 },
  scream_collection:  { name:"Scream",                type:"movie",  handler:"tmdb_collection", collectionId: 2602 },
  conjuring_coll:     { name:"The Conjuring",         type:"movie",  handler:"tmdb_collection", collectionId: 313086 },
  despicableme_coll:  { name:"Despicable Me",         type:"movie",  handler:"tmdb_collection", collectionId: 86066 },
  kungfupanda_coll:   { name:"Kung Fu Panda",         type:"movie",  handler:"tmdb_collection", collectionId: 77816 },
  incredibles_coll:   { name:"The Incredibles",       type:"movie",  handler:"tmdb_collection", collectionId: 468222 },
  deadpool_coll:      { name:"Deadpool",              type:"movie",  handler:"tmdb_collection", collectionId: 448150 },
  sherlock_coll:      { name:"Sherlock Holmes",       type:"movie",  handler:"tmdb_collection", collectionId: 102322 },
  findingnemo_coll:   { name:"Finding Nemo",          type:"movie",  handler:"tmdb_collection", collectionId: 137697 },
  toystory_coll:      { name:"Toy Story",             type:"movie",  handler:"tmdb_collection", collectionId: 10194 },
  backtofuture_coll:  { name:"Back to the Future",    type:"movie",  handler:"tmdb_collection", collectionId: 264 },
  matrix_collection:  { name:"The Matrix",            type:"movie",  handler:"tmdb_collection", collectionId: 2344 },
  diehard_collection: { name:"Die Hard",              type:"movie",  handler:"tmdb_collection", collectionId: 1570 },
  rambo_collection:   { name:"Rambo",                 type:"movie",  handler:"tmdb_collection", collectionId: 5039 },
  expendables_coll:   { name:"The Expendables",       type:"movie",  handler:"tmdb_collection", collectionId: 126125 },
  shrek2_collection:  { name:"Minions",               type:"movie",  handler:"tmdb_collection", collectionId: 544669 },
  dune_collection:    { name:"Dune",                   type:"movie",  handler:"tmdb_collection", collectionId: 726871 },
  godfather_collection:{ name:"The Godfather",         type:"movie",  handler:"tmdb_collection", collectionId: 230 },
  spiderman_collection:{ name:"Spider-Man",              type:"movie",  handler:"tmdb_multi_collection", collectionIds: [556, 531241, 573436] },
  avatar_collection:  { name:"Avatar",                   type:"movie",  handler:"tmdb_collection", collectionId: 87096 },
  scarymovie_coll:    { name:"Scary Movie",              type:"movie",  handler:"tmdb_collection", collectionId: 4246 },
  knivesout_coll:     { name:"Knives Out",               type:"movie",  handler:"tmdb_collection", collectionId: 722971 },
  mazerunner_coll:    { name:"Maze Runner",              type:"movie",  handler:"tmdb_collection", collectionId: 295130 },
  superman_collection:{ name:"Superman",               type:"movie",  handler:"tmdb_multi_collection", collectionIds: [8537, 209131, 1540907, 593251] },
  batman_collection:  { name:"Batman",                type:"movie",  handler:"tmdb_multi_collection", collectionIds: [120794, 263, 948485] },
  mdb_87667:  { name:"Trakt Trending",          type:"movie",  handler:"mdb" },
  mdb_88434:  { name:"Trakt Trending",          type:"series", handler:"mdb" },
  trakt_trending_movies:   { name:"Trakt Trending",    type:"movie",  handler:"trakt_trending" },
  trakt_trending_series:   { name:"Trakt Trending",    type:"series", handler:"trakt_trending" },
  trakt_popular_movies:    { name:"Trakt Popular",     type:"movie",  handler:"trakt_popular" },
  trakt_popular_series:    { name:"Trakt Popular",     type:"series", handler:"trakt_popular" },
  trakt_anticipated_movies:{ name:"Trakt Anticipated", type:"movie",  handler:"trakt_anticipated" },
  trakt_anticipated_series:{ name:"Trakt Anticipated", type:"series", handler:"trakt_anticipated" },
  trakt_fav_movies:        { name:"My Trakt Favorites",type:"movie",  handler:"trakt_user_favorites" },
  trakt_fav_series:        { name:"My Trakt Favorites",type:"series", handler:"trakt_user_favorites" },
  trakt_watchlist_movies:  { name:"My Trakt Watchlist",type:"movie",  handler:"trakt_user_watchlist" },
  trakt_watchlist_series:  { name:"My Trakt Watchlist",type:"series", handler:"trakt_user_watchlist" },
  trakt_collection_movies: { name:"My Trakt Collection",type:"movie", handler:"trakt_user_collection" },
  trakt_collection_series: { name:"My Trakt Collection",type:"series",handler:"trakt_user_collection" },
  mdb_2236:   { name:"Top Movies This Week",           type:"movie",  handler:"mdb" },
  mdb_1198:   { name:"Most Popular (Top 20)",          type:"movie",  handler:"mdb" },
  mdb_69:     { name:"IMDb Moviemeter Top 100",        type:"movie",  handler:"mdb" },
  mdb_86934:  { name:"Latest Digital Release",         type:"movie",  handler:"mdb" },
  mdb_960:    { name:"Latest Releases",                type:"movie",  handler:"mdb" },
  mdb_2202:   { name:"Latest Blu-ray Releases",        type:"movie",  handler:"mdb" },
  mdb_1176:   { name:"Latest Certified Fresh",         type:"movie",  handler:"mdb" },
  mdb_86710:  { name:"Latest Airing Shows",            type:"series", handler:"mdb" },
  mdb_88307:  { name:"Trending Kids",           type:"movie",  handler:"mdb" },
  mdb_88309:  { name:"Trending Kids",           type:"series", handler:"mdb" },
  mdb_13:     { name:"Top Kids Movies This Week",      type:"movie",  handler:"mdb" },
  mdb_88328:  { name:"Netflix Latest",          type:"movie",  handler:"mdb" },
  mdb_86751:  { name:"Netflix Latest",          type:"series", handler:"mdb" },
  mdb_86755:  { name:"Amazon Latest",           type:"movie",  handler:"mdb" },
  mdb_86753:  { name:"Amazon Latest",           type:"series", handler:"mdb" },
  mdb_88317:  { name:"Apple TV Plus Latest",    type:"movie",  handler:"mdb" },
  mdb_88319:  { name:"Apple TV Plus Latest",    type:"series", handler:"mdb" },
  mdb_86759:  { name:"Disney Plus Latest",      type:"movie",  handler:"mdb" },
  mdb_86758:  { name:"Disney Plus Latest",      type:"series", handler:"mdb" },
  mdb_89647:  { name:"HBO Latest",              type:"movie",  handler:"mdb" },
  mdb_89649:  { name:"HBO Latest",              type:"series", handler:"mdb" },
  mdb_86762:  { name:"Paramount Plus Latest",   type:"movie",  handler:"mdb" },
  mdb_86761:  { name:"Paramount Plus Latest",   type:"series", handler:"mdb" },
  mdb_88326:  { name:"Hulu Latest",             type:"movie",  handler:"mdb" },
  mdb_88327:  { name:"Hulu Latest",             type:"series", handler:"mdb" },
  mdb_84677:  { name:"Top Documentaries",              type:"movie",  handler:"mdb" },
  mdb_84403:  { name:"Documentary",         type:"series", handler:"mdb" },
  mdb_8043:   { name:"History & War",                type:"movie",  handler:"mdb" },
  mdb_84487:  { name:"Nature",                     type:"series", handler:"mdb" },
  mdb_84401:  { name:"Reality TV",                 type:"series", handler:"mdb" },
  mdb_83497:  { name:"Standup Comedy",             type:"movie",  handler:"mdb" },
  mdb_3892:   { name:"Must-See Mindfuck",              type:"movie",  handler:"mdb" },
  mdb_3923:   { name:"Crazy Plot Twists",              type:"movie",  handler:"mdb" },
  mdb_3920:   { name:"Outer Space",                    type:"movie",  handler:"mdb" },
  mdb_2909:   { name:"Time Travel",                    type:"movie",  handler:"mdb" },
  mdb_102554: { name:"Must-See Modern Horror",         type:"movie",  handler:"mdb" },
  mdb_2410:   { name:"Horror Classics",                type:"movie",  handler:"mdb" },
  mdb_3885:   { name:"100pct Rotten Tomatoes",         type:"movie",  handler:"mdb" },
  mdb_4081:   { name:"Top 50 Parody Movies",           type:"movie",  handler:"mdb" },
  mdb_4390:   { name:"True Crime Documentaries",       type:"movie",  handler:"mdb" },
  mdb_2858:   { name:"Thrilling Movies",               type:"movie",  handler:"mdb" },
  mdb_136620: { name:"Seasonal",                       type:"movie",  handler:"mdb" },
  mdb_3918:   { name:"Pixar Collection",               type:"movie",  handler:"mdb" },
  mdb_3928:   { name:"DreamWorks Collection",          type:"movie",  handler:"mdb" },
  mdb_3087:   { name:"BBC Shows",                      type:"series", handler:"mdb" },
  mdb_3091:   { name:"UK Shows",                       type:"series", handler:"mdb" },
  mdb_92337:  { name:"Best of 2025",                   type:"movie",  handler:"mdb" },
  mdb_91304:  { name:"Best of 2020s",                  type:"movie",  handler:"mdb" },
  mdb_91303:  { name:"Best of 2010s",                  type:"movie",  handler:"mdb" },
  mdb_91302:  { name:"Best of 2000s",                  type:"movie",  handler:"mdb" },
  mdb_91300:  { name:"Best of 1990s",                  type:"movie",  handler:"mdb" },
  mdb_91301:  { name:"Best of 1980s",                  type:"movie",  handler:"mdb" },
  search_movie: { name:"Ultra MAX", type:"movie",  handler:"search" },
  search_movies: { name:"Ultra MAX", type:"movie",  handler:"search" },
  search_series: { name:"Ultra MAX", type:"series", handler:"search" },

    // TV Collections / Universes
    got_tv_collection: { name:"Game of Thrones Universe", type:"series", handler:"tmdb_ids", ids:[1399, 94997] },
    sopranos_tv_collection:     { name:"The Sopranos",             type:"series", handler:"tmdb_search", query:"The Sopranos" },
    outlander_tv_collection:    { name:"Outlander",                type:"series", handler:"tmdb_search", query:"Outlander" },
    theboys_tv_collection: { name:"The Boys Universe", type:"series", handler:"tmdb_ids", ids:[76479, 205715] },
    breakingbad_tv_collection:  { name:"Breaking Bad Universe",    type:"series", handler:"tmdb_ids", ids:[1396, 60059] },
    yellowstone_tv_collection: { name:"Yellowstone Universe", type:"series", handler:"tmdb_ids", ids:[73586, 118357, 157744] },
    walkingdead_tv_collection: { name:"Walking Dead Universe", type:"series", handler:"tmdb_ids", ids:[1402, 62286, 211684, 194583, 206586] },
    dexter_tv_collection: { name:"Dexter Universe", type:"series", handler:"tmdb_ids", ids:[1405, 131927, 219937] },
    power_tv_collection: { name:"Power Universe", type:"series", handler:"tmdb_ids", ids:[54650, 97890, 124394, 119845] },

};

module.exports = {
  CATALOG_DEFS
};
